

---
- name: Jenkins Role
  hosts: jenkins
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install OpenJDK 17
      ansible.builtin.apt:
        name:
          - openjdk-17-jdk
        state: present

    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
        dest: "/usr/share/keyrings/jenkins-keyring.asc"

    - name: Create Jenkins repository file
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/jenkins.list"
        state: touch

    - name: Add Jenkins repository
      ansible.builtin.lineinfile:
        path: "/etc/apt/sources.list.d/jenkins.list"
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"

    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
